import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Add SF Pro Display fonts
const sfProDisplay = localFont({
  src: [
    {
      path: "./fonts/SF-Pro-Display-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    { path: "./fonts/SF-Pro-Display-Bold.otf", weight: "700", style: "normal" },
    {
      path: "./fonts/SF-Pro-Display-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Heavy.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-HeavyItalic.otf",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Light.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-LightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-SemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/SF-Pro-Display-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/SF-Pro-Display-ThinItalic.otf",
      weight: "100",
      style: "italic",
    },
  ],
  variable: "--font-sf-pro-display",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sfProDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
